
version: "3"
services:
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: adonis
      MYSQL_USER: adonis
      MYSQL_PASSWORD: adonis
      MYSQL_DATABASE: adonis
    networks:
        - app-network
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
    - .:/home/node/app
    ports:
    - 3333:3333
    depends_on:
      - db
    networks:
        - app-network
networks:
  app-network:
    driver: bridge